stages:
    - build
    - test
    - deploy

Build-Back:
    stage: build
    image: maven:3.6.3-jdk-11
    script:
        - echo "Building Backend"
        - cd CIBackend
        - mvn clean install -Dmaven.test.skip=true
        - docker build -f Dockerfile -t web-backend .
        - echo "Backend build complete"
    only:
        - master
        
Test-Junit:
  stage: test
  image: maven:3.6.3-jdk-11
  script:
    - cd CIBackend
    - mvn test
  only:
    - master
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

    
Test-sonar:
    stage: test
    image: docker:latest
    script: 
        - cd CIBackend
        - mvn clean verify
        - mvn sonar:sonar -Dsonar.host.url=http://142.93.53.2:9000/ -Dsonar.login=681db5b458e1b187825e95d8a5913cbd83e26a43
    only:
        - master
        
Deploy-Back:
    stage: deploy
    image: docker:latest
    services:
        - docker:dind
    only:
        - master
    script:
        - echo "Dedploying Backend"
        - cd Documentacion
        - docker-compose -f docker-compose.yml up -d
        - echo "Backend deployment complete"